sudo: required
services:
  - docker

before_install:
  - docker build -t freitasluizh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true freitasluizh/react-test npm test

after_success:
  - docker build -t freitasluizh/multi-client ./client
  - docker build -t freitasluizh/multi-nginx ./nginx
  - docker build -t freitasluizh/multi-server ./server
  - docker build -t freitasluizh/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_ID" --password-stdin
  - docker push freitasluizh/multi-client
  - docker push freitasluizh/multi-nginx
  - docker push freitasluizh/multi-server
  - docker push freitasluizh/multi-worker


deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-606255519617
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  